name: WorthItems
version: '1.0.0'
main: me.abdoabk.worth_items.Worth_items
api-version: '1.20'
description: Tier-based item pricing with hover tooltips and Vault sell support
authors: [3bdoabk]
softdepend: [Vault, Essentials]

commands:
  worth:
    description: Check the worth of an item
    usage: /worth [inventory|hand|inventory|reload]
    permission: worthitems.use

permissions:
  worthitems.use:
    description: Use /worth command
    default: true
  worthitems.reload:
    description: Reload price cache with /worth reload
    default: op